package com.stmarkssolutions.aws.cli.vpc.model.describe.networkinterfacepermissions

case class DescribeNetworkInterfacePermissionsResponse(NetworkInterfacePermissions:List[NetworkInterfacePermission])
